#pragma once

#define RES_WIDTH					1920
#define RES_HEIGHT					1080

#define COMMAND_COMPONENT_WIDTH		1920
#define COMMAND_COMPONENT_HEIGHT	1080

#define MAP_COMPONENT_DISPLAY_X		47
#define MAP_COMPONENT_DISPLAY_Y		33

#define MAP_COMPONENT_X				20
#define MAP_COMPONENT_Y				36
#define MAP_COMPONENT_WIDTH			1536
#define MAP_COMPONENT_HEIGHT		800

#define DATA_COMPONENT_X			1556
#define DATA_COMPONENT_Y			36
#define DATA_COMPONENT_WIDTH		338
#define DATA_COMPONENT_HEIGHT		798

#define MESSAGE_COMPONENT_X			20
#define MESSAGE_COMPONENT_Y			838

#define MAP_WIDTH					200
#define MAP_HEIGHT					200

#define TILE_WIDTH					32
#define TILE_HEIGHT					32

#define FORM_FONT_SIZE				15
